### PR TITLE
Api update

### PR DESCRIPTION
**Pull request by muety**

### CODE REVIEW

**Comment by jxsl13** [comment]
can you add some examples to the readme.

**Comment by jxsl13** [comment]
will review tomorrow.

**Comment by muety** [comment]
> can you add some examples to the readme.

Sure, I'll add some godoc comments to the code as well.

**Comment by jxsl13** [comment]
imo working with pointers is a pain in the butt.
Having nullable response values does rarely make sense and having pointers to slices does nearly never makes sense (in Go).

I updated the api spec manually that you can incorporate in this pr.
makes working with the response types more smoothly:


```yaml
openapi: 3.0.1
info:
  title: StromGedacht API
  termsOfService: https://www.stromgedacht.de/api-info/nutzungsbedingungen
  contact:
    url: https://www.stromgedacht.de
    email: stromgedacht@transnetbw.de
  version: v1
paths:
  /v1/forecast:
    get:
      tags:
        - RegionForecast
      summary: Returns requested forecast values for provided zip
      parameters:
        - name: zip
          in: query
          description: The zip code of the region where the data will be used
          required: true
          style: form
          schema:
            type: string
        - name: from
          in: query
          description: Data will be returned from this datetime on | This field is optional. By providing no date it uses the date 7 days ago | Only up to 7 days into the past can be requested
          style: form
          schema:
            type: string
            format: date-time
          example: '2023-09-12'
        - name: to
          in: query
          description: Data will be returned to this datetime | This field is optional. By providing no date it uses the date 1 day in the future | Only up to 1 day into the future can be requested
          style: form
          schema:
            type: string
            format: date-time
          example: '2023-09-18'
        - name: X-B2B-ID
          in: header
          description: Identifier of the business partner (B2B-ID) (Optional)
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForecastViewModel'
        '400':
          description: Missing query data or wrong date format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /v1/now:
    get:
      tags:
        - RegionStates
      summary: Returns current RegionState
      parameters:
        - name: zip
          in: query
          description: The zip code of the region where the data will be used
          required: true
          style: form
          schema:
            type: string
        - name: X-B2B-ID
          in: header
          description: Identifier of the business partner (B2B-ID) (Optional)
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionStateNowViewModel'
        '400':
          description: Missing query data or wrong date format
  /v1/states:
    get:
      tags:
        - RegionStates
      summary: Returns requested region states by provided dates
      parameters:
        - name: zip
          in: query
          description: The zip code of the region where the data will be used
          required: true
          style: form
          schema:
            type: string
        - name: from
          in: query
          description: Data will be returned from this datetime on | Only up to 4 days into the past can be requested
          required: true
          style: form
          schema:
            type: string
            format: date-time
          example: '2024-04-09T00:00:00+02:00'
        - name: to
          in: query
          description: Data will be returned to this datetime | Only up to 2 days into the future can be requested
          required: true
          style: form
          schema:
            type: string
            format: date-time
          example: '2024-04-15T23:59:59+02:00'
        - name: X-B2B-ID
          in: header
          description: Identifier of the business partner (B2B-ID) (Optional)
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionStateRangeViewModel'
        '400':
          description: Missing query data or wrong date format
  /v1/statesRelative:
    get:
      tags:
        - RegionStates
      summary: Returns requested region states by provided hours
      parameters:
        - name: zip
          in: query
          description: The zip code of the region where the data will be used
          required: true
          style: form
          schema:
            type: string
        - name: hoursInFuture
          in: query
          description: Data will be returned to the provided amount of hours in future | Only up to 2 days into the future can be requested
          required: true
          style: form
          schema:
            type: integer
            format: int32
        - name: hoursInPast
          in: query
          description: Data will be returned from the provided amount of hours in past | This field is optional | Only up to 4 days into the past can be requested
          style: form
          schema:
            type: integer
            format: int32
            default: 0
        - name: X-B2B-ID
          in: header
          description: Identifier of the business partner (B2B-ID) (Optional)
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionStateRangeViewModel'
        '400':
          description: Missing query data or wrong date format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    ForecastPointInTimeViewModel:
      required:
        -  dateTime
        -  value
      type: object
      properties:
        dateTime:
          type: string
          format: date-time
        value:
          type: number
          format: double
      additionalProperties: false
    ForecastViewModel:
      required:
        - load
        - renewableEnergy
        - residualLoad
        - superGreenThreshold
      type: object
      properties:
        load:
          type: array
          items:
            $ref: '#/components/schemas/ForecastPointInTimeViewModel'
        renewableEnergy:
          type: array
          items:
            $ref: '#/components/schemas/ForecastPointInTimeViewModel'
        residualLoad:
          type: array
          items:
            $ref: '#/components/schemas/ForecastPointInTimeViewModel'
        superGreenThreshold:
          type: array
          items:
            $ref: '#/components/schemas/ForecastPointInTimeViewModel'
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
      additionalProperties: { }
    RegionState:
      enum:
        - 1
        - 2
        - 3
        - 4
        - -1
      x-enum-varnames:
        - Green
        - Yellow
        - Orange
        - Red
        - SuperGreen
      type: integer
      format: int32
      description: "<p>Possible values:</p>\n<ul>\n<li><b>1</b> = green</li>\n<li><b>2</b> = yellow</li>\n<li><b>3</b> = orange</li>\n<li><b>4</b> = red</li>\n<li><b>-1</b> = superGreen</li>\n</ul>\n"
    RegionStateNowViewModel:
      required:
        -  state
      type: object
      properties:
        state:
          $ref: '#/components/schemas/RegionState'
      additionalProperties: false
    RegionStateRangeViewModel:
      required:
        -  states
      type: object
      properties:
        states:
          type: array
          items:
            $ref: '#/components/schemas/RegionStateViewModel'
      additionalProperties: false
    RegionStateViewModel:
      required:
        -  from
        -  to
        -  state
      type: object
      properties:
        from:
          type: string
          format: date-time
        to:
          type: string
          format: date-time
        state:
          $ref: '#/components/schemas/RegionState'
      additionalProperties: false
```

**Comment by muety** [comment]
Updated the API spec and adapted the code accordingly. Please review again.

**Comment by jxsl13** [comment]
I also thought about the pointer prameters `from` and `to`, but don't really have a good solution for those.

there are those two variants that you implememted, pointers and a special value for the default.
I can come up with another one where you use the options pattern to provide those `from` and `to` values as `WithFrom(time.Time)` or `WithTo(time.Time)` which might be slightly better?

I'm somewhat undecided in that regard. 
Do you have any preferences?

**Comment by muety** [comment]
I wasn't happy with the nil pointer references for `from` and `to` either, because (a) pointers to primitives seldomly make make much sense, and (b) were inconvenient to use (allocate variable, then pass pointer to it). But I think it's fine now as is. Of course, we could add "builder pattern-style" method like `WithX()` or have separate methods for the various combinations (too bad Go doesn't have method overloading in Go). But I wanted to find a good balance between convenience and not over-engineering things.

**Comment by jxsl13** [comment]
k, then we will go with this variant.

**Comment by jxsl13** [comment]
just some examples in the readme and this is ready to merge

**Pull request merged**
